name = "frostproject/threadpool"
description = "Pseudo code threadpool implementation for Luau to manage concurrent task execution."
version = "0.0.1"
authors = ["iceeburr <iceeburr@gmail.com> (https://iceeburr.dev)"]
repository = "https://github.com/frostproject/threadpool"
license = "MIT"
includes = ["README.md", "pesde.toml", "src/**/*.luau", "LICENSE"]

[target]
environment = "roblox"
lib = "src/main.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"
