name = "frostproject/threadpool"
description = "Pseudo code threadpool implementation for Luau to manage concurrent task execution."
version = "1.0.2"
authors = ["iceeburr <iceeburr@gmail.com> (https://iceeburr.dev)"]
repository = "https://github.com/frostproject/threadpool"
license = "MIT"
includes = ["README.md", "pesde.toml", "src/**/*.luau", "LICENSE"]

[engines]
pesde = "^0.7.0-rc.7"
lune = "0.8.9"

[target]
environment = "roblox"
lib = "src/main.luau"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/scripts_argon/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts_argon/sourcemap_generator.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
scripts_argon = { name = "frostproject/scripts_argon", version = "^0.0.6", target = "lune" }
argon = { name = "pesde/argon", version = "^2.0.25", target = "lune" }
